# Configurações básicas
spring.application.name=foodexplorer
server.port=3333

# COnfigurações de padronização
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.jackson.time-zone=America/Sao_Paulo

# Configurações de database
spring.datasource.url=jdbc:sqlite:foodexplorer.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.type.preferred_long_jdbc_type=INTEGER
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Pasta onde as imagens serão salvas fisicamente
file.upload.dir=uploads/images

# Limites do multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB