CREATE TABLE plates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    img VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL
);